name: CASEYRHODES-XMD

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes as a fallback

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  loop-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Cache npm dependencies for faster installs

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
            # Generate package-lock.json for future runs
            npm install --package-lock-only || echo "Failed to generate package-lock.json, continuing..."
          else
            echo "Error: package.json not found"
            exit 1
          fi

      - name: Run Bot (loop & auto-restart if crash)
        run: |
          echo "Running CASEYRHODES-XMD in auto-restart mode..."
          timeout 18000 bash -c 'while true; do npm start || { echo "Bot crashed with exit code $?, restarting..."; sleep 1; }; done'; [ $? -eq 124 ] && exit 0 || exit $?
        env:
          NODE_ENV: production

      - name: Re-Trigger Workflow
        if: success()
        run: |
          echo "Re-running workflow..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CASEYRHODES }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/CASEYRHODES-XMD.yml/dispatches \
            -d '{"ref":"main"}' || { echo "Re-trigger failed with exit code $?"; exit 1; }

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Workflow failed! Check logs for details."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CASEYRHODES }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"CASEYRHODES-XMD Workflow Failure","body":"Workflow failed at ${{ github.run_id }}. Check logs for details.","labels":["bug"]}'
